# Preliminary Mathematics

## Mathematical notations, sets, functions, exponents and logarithms

This section contains some basic important notations and conventions used in mathematics and statistics. 

### Numbers
- **Natural numbers, N**: numbers such as 0, 1, 3, ...
- **Integers, Z**: include negative numbers ..., -2, -1, 0, 1, 2
- **Rational numberes**: numbers that can be expressed as a ratio two integers, i.e. in a form $\frac{a}{b}$, where $a$ and $b$ are integers, and $b\neq0$
- **Real numbers, R**: include both rational and irrational numbers
- **Rreciprocal** of any number is found by diving 1 by the number, e.g. reciprocal of 5 is $\frac{1}{5}$
- **Absolute value** of a number can be viewed as its distance from zero, e.g. the absolute value of 6 is 6, written as $|6| = 6$ and absolute value of -5 is 5, written as $|-5| = 5$
- **Factorial** of a non-negative integer number $n$ is denoted by $n!$ and it is a product of all positive integers less than or equal to $n$, e.g. $4! = 4 \cdot 3\cdot 2 \cdot 1 = 24$

### Variables, constants and symbols
Mathematics gives us a precise language to communiate different concepts and ideas. To be able to use it it is essential to learn symbols and understand how they are used to represent physical quantities as well as understand the rules and conventions that have been developed to manipulate them. 

- **variables**: things that can vary, e.g. temperature and time
- **constants**: fixed and unchanging quantities used in certain calculations, e.g. 3.14159
- in principle one could freely choose letters and symbols to represent variables and constants, but it is helpful and choose letters and symbols that have meaning in a particular context. Hence, we
- $x, y, z$, the end of the alphabet is reserved for variables
- $a, b, c$, the beggining of the alphabet is used to reprsent constants
- $\pi$, $\omega$ and Greek letteres below are used frequently used to represent common constat, e.g. $\pi = 3.14159$

| Letter | Upper case | Lower case | Letter | Upper case | Lower case |
| :----------- | :----------- | :-------  | :----------- | :----------- | :-------  |
| Alpha | A | $\alpha$ | Nu | N | $\nu$ |  
| Beta | B | $\beta$ | Xi | $\Xi$ | $\xi$ |
| Gamma | $\Gamma$ | $\gamma$ | Omicron | O | o |
| Delta | $\Delta$ | $\delta$ | Pi | $\Pi$ | $\pi$ |
| Epsilon | E | $\epsilon$ | Rho | P | $\rho$ |
| Zeta | Z | $\zeta$ | Sigma | $\Sigma$ | $\sigma$ |
| Eta | H | $\eta$ | Tau | T | $\tau$ |
| Theta | $\Theta$ | $\theta$ | Upsilon | Y | $\upsilon$ |
| Iota | i | $\iota$ | Phi | $\Phi$ | $\phi$ | 
| Kappa | K | $\kappa$| Chi | $\Gamma$ | $\gamma$ |
| Lambda | $\Gamma$ | $\gamma$ | Psi | $\Psi$ | $\psi$ |
| Mu | M | $\mu$ | Omega | $\Omega$ | $\omega$ |
Table: (\#tab:greek-table) Greek alphabet

I am referring to Table \@ref(tab:greek-table)



<!-- ```{r table-test} -->

<!-- data.test <- matrix(c(1,2,3,4), nrow=2, ncol=2) -->
<!-- colnames(data.test) <- c("R1", "R2") -->

<!-- knitr::kable( -->
<!--   data.test, -->
<!--   booktabs = TRUE, -->
<!--   caption = 'A test table') -->

<!-- ``` -->

<!-- I am referring to Table \@ref(tab:table-test) -->

ss
## Differentiation
## Integration
## Vectors and Matrices




