---
title: "Introduction to biostatistics and machine learning"
author: "Olga Dethlefsen, Eva Freyhult, Bengt Sennblad, Payam Emami"
site: bookdown::bookdown_site
documentclass: book
date: "`r Sys.Date()`"  
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "Introduction to biostatistics and machine learning"
---

# Preface {-}

This "bookdown" book contains teaching and learning materials prepared and used during "Introduction to biostatistics and machine learning" course organised by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees in need of biostatistical skills within Swedish universities.  The materials are geared towards life scientists wanting to be able to understand and use basic statistical and machine learning methods. It may also suits those already applying biostatistical methods but who have never gotten a chance to reflect on the basic statistical concepts, such as the commonly misinterpreted p-value. 

More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)

