<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Generalized linear models | Introduction to biostatistics and machine learning</title>
  <meta name="description" content="Chapter 11 Generalized linear models | Introduction to biostatistics and machine learning" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Generalized linear models | Introduction to biostatistics and machine learning" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Chapter 11 Generalized linear models | Introduction to biostatistics and machine learning" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Generalized linear models | Introduction to biostatistics and machine learning" />
  
  <meta name="twitter:description" content="Chapter 11 Generalized linear models | Introduction to biostatistics and machine learning" />
  

<meta name="author" content="Olga Dethlefsen, Eva Freyhult, Bengt Sennblad, Payam Emami" />


<meta name="date" content="2020-11-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="model-summary-assumptions.html"/>
<link rel="next" href="classification-with-knn-and-decision-trees.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to biostatistics and machine learning</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>I Preliminary Mathematics</b></span></li>
<li class="chapter" data-level="1" data-path="mathematical-notations.html"><a href="mathematical-notations.html"><i class="fa fa-check"></i><b>1</b> Mathematical notations</a>
<ul>
<li class="chapter" data-level="1.1" data-path="mathematical-notations.html"><a href="mathematical-notations.html#numbers"><i class="fa fa-check"></i><b>1.1</b> Numbers</a></li>
<li class="chapter" data-level="1.2" data-path="mathematical-notations.html"><a href="mathematical-notations.html#variables-constants-and-letters"><i class="fa fa-check"></i><b>1.2</b> Variables, constants and letters</a></li>
<li class="chapter" data-level="1.3" data-path="mathematical-notations.html"><a href="mathematical-notations.html#a-precise-language"><i class="fa fa-check"></i><b>1.3</b> A precise language</a></li>
<li class="chapter" data-level="1.4" data-path="mathematical-notations.html"><a href="mathematical-notations.html#using-symbols"><i class="fa fa-check"></i><b>1.4</b> Using symbols</a></li>
<li class="chapter" data-level="1.5" data-path="mathematical-notations.html"><a href="mathematical-notations.html#inequalities"><i class="fa fa-check"></i><b>1.5</b> Inequalities</a></li>
<li class="chapter" data-level="1.6" data-path="mathematical-notations.html"><a href="mathematical-notations.html#indices-and-powers"><i class="fa fa-check"></i><b>1.6</b> Indices and powers</a></li>
<li class="chapter" data-level="1.7" data-path="mathematical-notations.html"><a href="mathematical-notations.html#exercises-notations"><i class="fa fa-check"></i><b>1.7</b> Exercises: notations</a></li>
<li class="chapter" data-level="" data-path="mathematical-notations.html"><a href="mathematical-notations.html#answers-to-selected-exercises-notations"><i class="fa fa-check"></i>Answers to selected exercises (notations)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sets.html"><a href="sets.html"><i class="fa fa-check"></i><b>2</b> Sets</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sets.html"><a href="sets.html#definitions"><i class="fa fa-check"></i><b>2.1</b> Definitions</a></li>
<li class="chapter" data-level="2.2" data-path="sets.html"><a href="sets.html#basic-set-operations"><i class="fa fa-check"></i><b>2.2</b> Basic set operations</a></li>
<li class="chapter" data-level="2.3" data-path="sets.html"><a href="sets.html#venn-diagrams"><i class="fa fa-check"></i><b>2.3</b> Venn diagrams</a></li>
<li class="chapter" data-level="2.4" data-path="sets.html"><a href="sets.html#exercises-sets"><i class="fa fa-check"></i><b>2.4</b> Exercises: sets</a></li>
<li class="chapter" data-level="" data-path="sets.html"><a href="sets.html#answers-to-selected-exercises-sets"><i class="fa fa-check"></i>Answers to selected exercises (sets)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>3</b> Functions</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sets.html"><a href="sets.html#definitions"><i class="fa fa-check"></i><b>3.1</b> Definitions</a></li>
<li class="chapter" data-level="3.2" data-path="functions.html"><a href="functions.html#evaluating-function"><i class="fa fa-check"></i><b>3.2</b> Evaluating function</a></li>
<li class="chapter" data-level="3.3" data-path="functions.html"><a href="functions.html#plotting-function"><i class="fa fa-check"></i><b>3.3</b> Plotting function</a></li>
<li class="chapter" data-level="3.4" data-path="functions.html"><a href="functions.html#standard-classes-of-functions"><i class="fa fa-check"></i><b>3.4</b> Standard classes of functions</a></li>
<li class="chapter" data-level="3.5" data-path="functions.html"><a href="functions.html#piecewise-functions"><i class="fa fa-check"></i><b>3.5</b> Piecewise functions</a></li>
<li class="chapter" data-level="3.6" data-path="functions.html"><a href="functions.html#exercises-functions"><i class="fa fa-check"></i><b>3.6</b> Exercises: functions</a></li>
<li class="chapter" data-level="" data-path="functions.html"><a href="functions.html#answers-to-selected-exercises-functions"><i class="fa fa-check"></i>Answers to selected exercises (functions)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="differentiation.html"><a href="differentiation.html"><i class="fa fa-check"></i><b>4</b> Differentiation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="differentiation.html"><a href="differentiation.html#rate-of-change"><i class="fa fa-check"></i><b>4.1</b> Rate of change</a></li>
<li class="chapter" data-level="4.2" data-path="differentiation.html"><a href="differentiation.html#average-rate-of-change-across-an-interval"><i class="fa fa-check"></i><b>4.2</b> Average rate of change across an interval</a></li>
<li class="chapter" data-level="4.3" data-path="differentiation.html"><a href="differentiation.html#rate-of-change-at-a-point"><i class="fa fa-check"></i><b>4.3</b> Rate of change at a point</a></li>
<li class="chapter" data-level="4.4" data-path="differentiation.html"><a href="differentiation.html#terminology-and-notation"><i class="fa fa-check"></i><b>4.4</b> Terminology and notation</a></li>
<li class="chapter" data-level="4.5" data-path="differentiation.html"><a href="differentiation.html#table-of-derivatives"><i class="fa fa-check"></i><b>4.5</b> Table of derivatives</a></li>
<li class="chapter" data-level="4.6" data-path="differentiation.html"><a href="differentiation.html#exercises-differentiation"><i class="fa fa-check"></i><b>4.6</b> Exercises (differentiation)</a></li>
<li class="chapter" data-level="" data-path="differentiation.html"><a href="differentiation.html#answers-to-selected-exercises-differentiation"><i class="fa fa-check"></i>Answers to selected exercises (differentiation)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="integration.html"><a href="integration.html"><i class="fa fa-check"></i><b>5</b> Integration</a>
<ul>
<li class="chapter" data-level="5.1" data-path="integration.html"><a href="integration.html#reverse-to-differentiation"><i class="fa fa-check"></i><b>5.1</b> Reverse to differentiation</a></li>
<li class="chapter" data-level="5.2" data-path="integration.html"><a href="integration.html#what-is-constant-of-integration"><i class="fa fa-check"></i><b>5.2</b> What is constant of integration?</a></li>
<li class="chapter" data-level="5.3" data-path="integration.html"><a href="integration.html#table-of-integrals"><i class="fa fa-check"></i><b>5.3</b> Table of integrals</a></li>
<li class="chapter" data-level="5.4" data-path="integration.html"><a href="integration.html#definite-integrals"><i class="fa fa-check"></i><b>5.4</b> Definite integrals</a></li>
<li class="chapter" data-level="5.5" data-path="integration.html"><a href="integration.html#exercises-integration"><i class="fa fa-check"></i><b>5.5</b> Exercises (integration)</a></li>
<li class="chapter" data-level="" data-path="integration.html"><a href="integration.html#answers-to-selected-exercises-integration"><i class="fa fa-check"></i>Answers to selected exercises (integration)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="vectors.html"><a href="vectors.html"><i class="fa fa-check"></i><b>6</b> Vectors</a>
<ul>
<li class="chapter" data-level="6.1" data-path="vectors.html"><a href="vectors.html#vectors-1"><i class="fa fa-check"></i><b>6.1</b> Vectors</a></li>
<li class="chapter" data-level="6.2" data-path="vectors.html"><a href="vectors.html#operations-on-vectors"><i class="fa fa-check"></i><b>6.2</b> Operations on vectors</a></li>
<li class="chapter" data-level="6.3" data-path="vectors.html"><a href="vectors.html#null-and-unit-vector"><i class="fa fa-check"></i><b>6.3</b> Null and unit vector</a></li>
<li class="chapter" data-level="" data-path="vectors.html"><a href="vectors.html#answers-to-selected-exercises-vectors-and-matrices"><i class="fa fa-check"></i>Answers to selected exercises (vectors and matrices)</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="matrices.html"><a href="matrices.html"><i class="fa fa-check"></i><b>7</b> Matrices</a>
<ul>
<li class="chapter" data-level="7.1" data-path="matrices.html"><a href="matrices.html#matrix"><i class="fa fa-check"></i><b>7.1</b> Matrix</a></li>
<li class="chapter" data-level="7.2" data-path="matrices.html"><a href="matrices.html#special-matrices"><i class="fa fa-check"></i><b>7.2</b> Special matrices</a></li>
<li class="chapter" data-level="7.3" data-path="matrices.html"><a href="matrices.html#matrix-operations"><i class="fa fa-check"></i><b>7.3</b> Matrix operations</a></li>
<li class="chapter" data-level="7.4" data-path="matrices.html"><a href="matrices.html#inverse-of-a-matrix"><i class="fa fa-check"></i><b>7.4</b> Inverse of a matrix</a></li>
<li class="chapter" data-level="7.5" data-path="matrices.html"><a href="matrices.html#orthogonal-matrix"><i class="fa fa-check"></i><b>7.5</b> Orthogonal matrix</a></li>
<li class="chapter" data-level="" data-path="matrices.html"><a href="matrices.html#answers-to-selected-exercises-matrices"><i class="fa fa-check"></i>Answers to selected exercises (matrices)</a></li>
</ul></li>
<li class="part"><span><b>II Linear Models</b></span></li>
<li class="chapter" data-level="8" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html"><i class="fa fa-check"></i><b>8</b> Introduction to linear models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#statistical-vs.-deterministic-relationship"><i class="fa fa-check"></i><b>8.1</b> Statistical vs. deterministic relationship</a></li>
<li class="chapter" data-level="8.2" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#what-linear-models-are-and-are-not"><i class="fa fa-check"></i><b>8.2</b> What linear models are and are not</a></li>
<li class="chapter" data-level="8.3" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#terminology"><i class="fa fa-check"></i><b>8.3</b> Terminology</a></li>
<li class="chapter" data-level="8.4" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#with-linear-models-we-can-answer-questions-such-as"><i class="fa fa-check"></i><b>8.4</b> With linear models we can answer questions such as:</a></li>
<li class="chapter" data-level="8.5" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.5</b> Simple linear regression</a></li>
<li class="chapter" data-level="8.6" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#least-squares"><i class="fa fa-check"></i><b>8.6</b> Least squares</a></li>
<li class="chapter" data-level="8.7" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#intercept-and-slope"><i class="fa fa-check"></i><b>8.7</b> Intercept and Slope</a></li>
<li class="chapter" data-level="8.8" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#hypothesis-testing"><i class="fa fa-check"></i><b>8.8</b> Hypothesis testing</a></li>
<li class="chapter" data-level="8.9" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#vector-matrix-notations"><i class="fa fa-check"></i><b>8.9</b> Vector-matrix notations</a></li>
<li class="chapter" data-level="8.10" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#confidence-intervals-and-prediction-intervals"><i class="fa fa-check"></i><b>8.10</b> Confidence intervals and prediction intervals</a></li>
<li class="chapter" data-level="8.11" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#exercises-linear-models-i"><i class="fa fa-check"></i><b>8.11</b> Exercises: linear models I</a></li>
<li class="chapter" data-level="" data-path="introduction-to-linear-models.html"><a href="introduction-to-linear-models.html#answers-to-selected-exercises-linear-models"><i class="fa fa-check"></i>Answers to selected exercises (linear models)</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression-coefficients.html"><a href="regression-coefficients.html"><i class="fa fa-check"></i><b>9</b> Regression coefficients</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression-coefficients.html"><a href="regression-coefficients.html#interpreting-and-using-linear-regression-models"><i class="fa fa-check"></i><b>9.1</b> Interpreting and using linear regression models</a></li>
<li class="chapter" data-level="9.2" data-path="regression-coefficients.html"><a href="regression-coefficients.html#example-plasma-volume"><i class="fa fa-check"></i><b>9.2</b> Example: plasma volume</a></li>
<li class="chapter" data-level="9.3" data-path="regression-coefficients.html"><a href="regression-coefficients.html#example-galapagos-islands"><i class="fa fa-check"></i><b>9.3</b> Example: Galapagos Islands</a></li>
<li class="chapter" data-level="9.4" data-path="regression-coefficients.html"><a href="regression-coefficients.html#example-height-and-gender"><i class="fa fa-check"></i><b>9.4</b> Example: Height and gender</a></li>
<li class="chapter" data-level="9.5" data-path="regression-coefficients.html"><a href="regression-coefficients.html#example-heigth-weight-and-gender-i"><i class="fa fa-check"></i><b>9.5</b> Example: Heigth, weight and gender I</a></li>
<li class="chapter" data-level="9.6" data-path="regression-coefficients.html"><a href="regression-coefficients.html#example-heigth-weight-and-gender-ii"><i class="fa fa-check"></i><b>9.6</b> Example: Heigth, weight and gender II</a></li>
<li class="chapter" data-level="9.7" data-path="regression-coefficients.html"><a href="regression-coefficients.html#exercises-linear-models-ii"><i class="fa fa-check"></i><b>9.7</b> Exercises: linear models II</a></li>
<li class="chapter" data-level="" data-path="regression-coefficients.html"><a href="regression-coefficients.html#answers-to-selected-exercises-linear-models-ii"><i class="fa fa-check"></i>Answers to selected exercises (linear models II)</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html"><i class="fa fa-check"></i><b>10</b> Model summary &amp; assumptions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#assessing-model-fit"><i class="fa fa-check"></i><b>10.1</b> Assessing model fit</a></li>
<li class="chapter" data-level="10.2" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#r2-summary-of-the-fitted-model"><i class="fa fa-check"></i><b>10.2</b> <span class="math inline">\(R^2\)</span>: summary of the fitted model</a></li>
<li class="chapter" data-level="10.3" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#r2-and-correlation-coefficient"><i class="fa fa-check"></i><b>10.3</b> <span class="math inline">\(R^2\)</span> and correlation coefficient</a></li>
<li class="chapter" data-level="10.4" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#r2adj"><i class="fa fa-check"></i><b>10.4</b> <span class="math inline">\(R^2(adj)\)</span></a></li>
<li class="chapter" data-level="10.5" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#the-assumptions-of-a-linear-model"><i class="fa fa-check"></i><b>10.5</b> The assumptions of a linear model</a></li>
<li class="chapter" data-level="10.6" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#checking-assumptions"><i class="fa fa-check"></i><b>10.6</b> Checking assumptions</a></li>
<li class="chapter" data-level="10.7" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#influential-observations"><i class="fa fa-check"></i><b>10.7</b> Influential observations</a></li>
<li class="chapter" data-level="10.8" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#exercises-linear-models-iii"><i class="fa fa-check"></i><b>10.8</b> Exercises: linear models III</a></li>
<li class="chapter" data-level="" data-path="model-summary-assumptions.html"><a href="model-summary-assumptions.html#answers-to-selected-exercises-linear-models-iii"><i class="fa fa-check"></i>Answers to selected exercises (linear models III)</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>11</b> Generalized linear models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#why-generalized-linear-models-glms"><i class="fa fa-check"></i><b>11.1</b> Why Generalized Linear Models (GLMs)</a></li>
<li class="chapter" data-level="11.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#warm-up"><i class="fa fa-check"></i><b>11.2</b> Warm-up</a></li>
<li class="chapter" data-level="11.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logisitc-regression"><i class="fa fa-check"></i><b>11.3</b> Logisitc regression</a></li>
<li class="chapter" data-level="11.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>11.4</b> Poisson regression</a></li>
<li class="chapter" data-level="11.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#exercises-glms"><i class="fa fa-check"></i><b>11.5</b> Exercises (GLMs)</a></li>
</ul></li>
<li class="part"><span><b>III Misc</b></span></li>
<li class="chapter" data-level="12" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html"><i class="fa fa-check"></i><b>12</b> Classification with knn and decision trees</a>
<ul>
<li class="chapter" data-level="12.1" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html#classification"><i class="fa fa-check"></i><b>12.1</b> Classification</a></li>
<li class="chapter" data-level="12.2" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html#evaluating-classification-model-performance"><i class="fa fa-check"></i><b>12.2</b> Evaluating Classification Model Performance</a></li>
<li class="chapter" data-level="12.3" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html#data-splitting"><i class="fa fa-check"></i><b>12.3</b> Data splitting</a></li>
<li class="chapter" data-level="12.4" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html#cross-validation"><i class="fa fa-check"></i><b>12.4</b> Cross validation</a></li>
<li class="chapter" data-level="12.5" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html#k-nearest-neighbours"><i class="fa fa-check"></i><b>12.5</b> k-nearest neighbours</a></li>
<li class="chapter" data-level="12.6" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html#classification-trees"><i class="fa fa-check"></i><b>12.6</b> Classification trees</a></li>
<li class="chapter" data-level="12.7" data-path="classification-with-knn-and-decision-trees.html"><a href="classification-with-knn-and-decision-trees.html#exercises-classification"><i class="fa fa-check"></i><b>12.7</b> Exercises: classification</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html"><i class="fa fa-check"></i><b>13</b> ANN regression and classification</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#exercise-1.1"><i class="fa fa-check"></i><b>13.1</b> Exercise 1.1</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#set-up"><i class="fa fa-check"></i><b>13.1.1</b> Set-up</a></li>
<li class="chapter" data-level="13.1.2" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#load-and-process-the-data"><i class="fa fa-check"></i><b>13.1.2</b> Load and process the data</a></li>
<li class="chapter" data-level="13.1.3" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#data-split"><i class="fa fa-check"></i><b>13.1.3</b> Data split</a></li>
<li class="chapter" data-level="13.1.4" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#default-knn-decision-tree-and-logistic-regression-classification"><i class="fa fa-check"></i><b>13.1.4</b> Default knn, decision tree and logistic regression classification</a></li>
<li class="chapter" data-level="13.1.5" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#ann-classification-fitting-model"><i class="fa fa-check"></i><b>13.1.5</b> ANN classification: fitting model</a></li>
<li class="chapter" data-level="13.1.6" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#ann-classification-comparering-to-logistic-regression"><i class="fa fa-check"></i><b>13.1.6</b> ANN classification: comparering to logistic regression</a></li>
<li class="chapter" data-level="13.1.7" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#ann-classification-adding-hidden-layers"><i class="fa fa-check"></i><b>13.1.7</b> ANN classification: adding hidden layers</a></li>
<li class="chapter" data-level="13.1.8" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#ann-classification-changing-activation-function"><i class="fa fa-check"></i><b>13.1.8</b> ANN classification: changing activation function</a></li>
<li class="chapter" data-level="13.1.9" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#ann-regression"><i class="fa fa-check"></i><b>13.1.9</b> ANN regression</a></li>
<li class="chapter" data-level="13.1.10" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#ann-rep-value"><i class="fa fa-check"></i><b>13.1.10</b> ANN rep value</a></li>
<li class="chapter" data-level="13.1.11" data-path="ann-regression-and-classification.html"><a href="ann-regression-and-classification.html#ann-relative-importance-of-variables"><i class="fa fa-check"></i><b>13.1.11</b> ANN relative importance of variables</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to biostatistics and machine learning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="generalized-linear-models" class="section level1" number="11">
<h1><span class="header-section-number">Chapter 11</span> Generalized linear models</h1>
<p><strong>Aims</strong></p>
<ul>
<li>to briefly introduce GLMs via examples of modeling binary and count response</li>
</ul>
<p><strong>Learning outcomes</strong></p>
<ul>
<li>to understand the limits of linear regression and the application of GLMs</li>
<li>to be able to use glm() function to fit and interpret logistic and Poisson regression</li>
</ul>
<div id="why-generalized-linear-models-glms" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> Why Generalized Linear Models (GLMs)</h2>
<ul>
<li>GLMs extend linear model framework to outcome variables that do not follow normal distribution</li>
<li>They are most frequently used to model binary, categorical or count data</li>
<li>In the Galapagos Island example we have tried to model Species using linear model</li>
<li>It kind of worked but the predicted counts were not counts (natural numbers) but rational numbers instead that make no sense when taking about count data</li>
<li>Similarly, fitting a regression line to binary data yields predicted values that could take any value, including <span class="math inline">\(&lt;0\)</span></li>
<li>not to mention that it is hard to argue that the values of 0 and 1s are normally distributed</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-2"></span>
<img src="304-linear-GLM_files/figure-html/unnamed-chunk-2-1.png" alt="Example of fitting linear model to binary data, to model the acceptance to medical school, coded as 1 (Yes) and 0 (No) using GPA school scores. Linear model does not fit the data well in this case" width="384" />
<p class="caption">
Figure 3.3: Example of fitting linear model to binary data, to model the acceptance to medical school, coded as 1 (Yes) and 0 (No) using GPA school scores. Linear model does not fit the data well in this case
</p>
</div>
</div>
<div id="warm-up" class="section level2" number="11.2">
<h2><span class="header-section-number">11.2</span> Warm-up</h2>
<ul>
<li>go to the form
<a href="https://forms.gle/wKcZns85D9AN86KD6">https://forms.gle/wKcZns85D9AN86KD6</a></li>
<li>there is a link to <a href="https://www.theguardian.com/global/video/2018/may/16/what-do-you-hear-in-this-audio-clip-yanny-or-laurel-takes-internet-by-storm-video">a short video</a>.</li>
<li>list to the video, what do you hear to begin with? Answer the question in the form and give us a little bit insignificant information about yourself (it is anonymous).</li>
</ul>
</div>
<div id="logisitc-regression" class="section level2" number="11.3">
<h2><span class="header-section-number">11.3</span> Logisitc regression</h2>
<ul>
<li>Yanny or Laurel auditory illusion appeared online in May 2018. You could find lots of information about it, together with some plausible explanations why some people hear Yanny and some year Laurel</li>
<li>One of the explanation is that with age we lose the ability to hear certain sounds</li>
<li>To see if there is evidence for that, someone has already collected some data for 53 people including their age and gender</li>
</ul>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="generalized-linear-models.html#cb46-1" aria-hidden="true"></a><span class="co"># Read in and preview data</span></span>
<span id="cb46-2"><a href="generalized-linear-models.html#cb46-2" aria-hidden="true"></a>yl &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/lm/yanny-laurel.csv&quot;</span>)</span>
<span id="cb46-3"><a href="generalized-linear-models.html#cb46-3" aria-hidden="true"></a><span class="kw">head</span>(yl)</span>
<span id="cb46-4"><a href="generalized-linear-models.html#cb46-4" aria-hidden="true"></a><span class="co">##     hear age gender</span></span>
<span id="cb46-5"><a href="generalized-linear-models.html#cb46-5" aria-hidden="true"></a><span class="co">## 1  Yanny  40 Female</span></span>
<span id="cb46-6"><a href="generalized-linear-models.html#cb46-6" aria-hidden="true"></a><span class="co">## 2  Yanny  48   Male</span></span>
<span id="cb46-7"><a href="generalized-linear-models.html#cb46-7" aria-hidden="true"></a><span class="co">## 3  Yanny  32 Female</span></span>
<span id="cb46-8"><a href="generalized-linear-models.html#cb46-8" aria-hidden="true"></a><span class="co">## 4 Laurel  47 Female</span></span>
<span id="cb46-9"><a href="generalized-linear-models.html#cb46-9" aria-hidden="true"></a><span class="co">## 5 Laurel  60   Male</span></span>
<span id="cb46-10"><a href="generalized-linear-models.html#cb46-10" aria-hidden="true"></a><span class="co">## 6  Yanny  11 Female</span></span>
<span id="cb46-11"><a href="generalized-linear-models.html#cb46-11" aria-hidden="true"></a></span>
<span id="cb46-12"><a href="generalized-linear-models.html#cb46-12" aria-hidden="true"></a><span class="co"># Recode Laurel to 0 and Yanny as 1 in new variable (what)</span></span>
<span id="cb46-13"><a href="generalized-linear-models.html#cb46-13" aria-hidden="true"></a>yl<span class="op">$</span>word &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb46-14"><a href="generalized-linear-models.html#cb46-14" aria-hidden="true"></a>yl<span class="op">$</span>word[yl<span class="op">$</span>hear<span class="op">==</span><span class="st">&quot;Laurel&quot;</span>] &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb46-15"><a href="generalized-linear-models.html#cb46-15" aria-hidden="true"></a></span>
<span id="cb46-16"><a href="generalized-linear-models.html#cb46-16" aria-hidden="true"></a><span class="co"># Make some exploratory plots</span></span>
<span id="cb46-17"><a href="generalized-linear-models.html#cb46-17" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb46-18"><a href="generalized-linear-models.html#cb46-18" aria-hidden="true"></a><span class="kw">plot</span>(yl<span class="op">$</span>age, yl<span class="op">$</span>word, <span class="dt">pch=</span><span class="dv">19</span>, <span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;&quot;</span>, <span class="dt">las=</span><span class="dv">1</span>)</span>
<span id="cb46-19"><a href="generalized-linear-models.html#cb46-19" aria-hidden="true"></a><span class="kw">boxplot</span>(yl<span class="op">$</span>age<span class="op">~</span>yl<span class="op">$</span>hear, <span class="dt">xlab=</span><span class="st">&quot;&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">col=</span><span class="st">&quot;lightblue&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-4"></span>
<img src="304-linear-GLM_files/figure-html/unnamed-chunk-4-1.png" alt="Yanny and Laurel auditory illusion data, Yanny (1), Luarel (0)" width="768" />
<p class="caption">
Figure 3.5: Yanny and Laurel auditory illusion data, Yanny (1), Luarel (0)
</p>
</div>
<ul>
<li>Since the response variable takes only two values (Yanny or Laurel) we use GLM model</li>
<li>to fit <strong>logistic regression</strong> model for the <strong>probability of hearing Yanny</strong></li>
<li>we let <span class="math inline">\(p_i=P(Y_i=1)\)</span> denote the probability of hearing Yanny</li>
<li>we further assume that <span class="math inline">\(Y_i \sim Bin(1, p_i)\)</span> distribution with
<span class="math display">\[log(\frac{p_i}{1-p_i})=\beta_0 + \beta_1x_i\]</span>
this is equivalent to:
<span class="math display">\[p_i = \frac{exp(\beta_0 + \beta_1x_i)}{1 + exp(\beta_0 + \beta_1x_i)}\]</span></li>
<li><strong>link function</strong> <span class="math inline">\(log(\frac{p_i}{1-p_i})\)</span> provides the link between the distribution of <span class="math inline">\(Y_i\)</span> and the linear predictor <span class="math inline">\(\eta_i\)</span></li>
<li><strong>GLM model</strong> can be written as <span class="math inline">\(g(\mu_i)=\eta_i = \mathbf{X}\boldsymbol\beta\)</span></li>
<li>we use <code>glm()</code> function in R to fit GLM models</li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="generalized-linear-models.html#cb47-1" aria-hidden="true"></a><span class="co"># fit logistic regression model</span></span>
<span id="cb47-2"><a href="generalized-linear-models.html#cb47-2" aria-hidden="true"></a>logmodel<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(word <span class="op">~</span><span class="st"> </span>age, <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link=</span><span class="st">&quot;logit&quot;</span>), <span class="dt">data =</span> yl)</span>
<span id="cb47-3"><a href="generalized-linear-models.html#cb47-3" aria-hidden="true"></a></span>
<span id="cb47-4"><a href="generalized-linear-models.html#cb47-4" aria-hidden="true"></a><span class="co"># print model summary</span></span>
<span id="cb47-5"><a href="generalized-linear-models.html#cb47-5" aria-hidden="true"></a><span class="kw">print</span>(<span class="kw">summary</span>(logmodel<span class="fl">.1</span>))</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = word ~ age, family = binomial(link = &quot;logit&quot;), 
##     data = yl)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -1.86068  -0.71414  -0.04733   0.64434   2.47887  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.56159    0.95790  -3.718 0.000201 ***
## age          0.08943    0.02297   3.893 9.89e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 83.178  on 59  degrees of freedom
## Residual deviance: 57.967  on 58  degrees of freedom
## AIC: 61.967
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="generalized-linear-models.html#cb49-1" aria-hidden="true"></a><span class="co"># plot</span></span>
<span id="cb49-2"><a href="generalized-linear-models.html#cb49-2" aria-hidden="true"></a><span class="kw">ggPredict</span>(logmodel<span class="fl">.1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-5"></span>
<img src="304-linear-GLM_files/figure-html/unnamed-chunk-5-1.png" alt="Fitted logistic model to the Yanny and Laurel data" width="384" />
<p class="caption">
Figure 11.1: Fitted logistic model to the Yanny and Laurel data
</p>
</div>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="generalized-linear-models.html#cb50-1" aria-hidden="true"></a><span class="co"># to get predictions use predict() functions</span></span>
<span id="cb50-2"><a href="generalized-linear-models.html#cb50-2" aria-hidden="true"></a><span class="co"># if no new observations is specified predictions are returned for the values of exploratory variables used</span></span>
<span id="cb50-3"><a href="generalized-linear-models.html#cb50-3" aria-hidden="true"></a><span class="co"># we specify response to return prediction on the probability scale</span></span>
<span id="cb50-4"><a href="generalized-linear-models.html#cb50-4" aria-hidden="true"></a><span class="kw">predict</span>(logmodel<span class="fl">.1</span>, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##          1          2          3          4          5          6          7 
## 0.50394192 0.67507724 0.33187793 0.65516152 0.85868941 0.07057982 0.87903410 
##          8          9         10         11         12         13         14 
## 0.06493370 0.35199768 0.69437930 0.91222027 0.15663558 0.78037334 0.43719992 
##         15         16         17         18         19         20         21 
## 0.39379165 0.59230535 0.20986467 0.45931517 0.69437930 0.22507939 0.48159183 
##         22         23         24         25         26         27         28 
## 0.20986467 0.71302217 0.10615359 0.97322447 0.65516152 0.11494328 0.20986467 
##         29         30         31         32         33         34         35 
## 0.12435950 0.90478991 0.87903410 0.93146108 0.15663558 0.18173908 0.33187793 
##         36         37         38         39         40         41         42 
## 0.59230535 0.94673070 0.06493370 0.82290366 0.91222027 0.82290366 0.92552645 
##         43         44         45         46         47         48         49 
## 0.83556313 0.04630975 0.50394192 0.37265683 0.97751124 0.45931517 0.41533155 
##         50         51         52         53         54         55         56 
## 0.35199768 0.04630975 0.83556313 0.15663558 0.20986467 0.22507939 0.15663558 
##         57         58         59         60 
## 0.73096842 0.35199768 0.43719992 0.87903410</code></pre>
<ul>
<li>The regression equation for the fitted model is:
<span class="math display">\[log(\frac{\hat{p_i}}{1-\hat{p_i}})=-3.56  +  0.09x_i\]</span></li>
<li>we see from the output that <span class="math inline">\(\hat{\beta_0} = -3.56\)</span> and <span class="math inline">\(\hat{\beta_1} = 0.09\)</span></li>
<li>these estimates are arrived at via maximum likelihood estimation, something that is out of scope here</li>
<li>but similarly to linear models, we can test the null hypothesis <span class="math inline">\(H_0:\beta_1=0\)</span> by comparing, <span class="math inline">\(z = \frac{\hat{\beta_1}}{e.s.e(\hat{\beta_1)}} = 3.89\)</span> with a standard normal distribution, <strong>Wald test</strong>, and the associated value is small meaning that there is enough evidence to reject the null, meaning that age is significantly associated with the probability with hearing Laurel and Yanny</li>
<li>the same conclusion can be reached if we compare the <strong>residual deviance</strong></li>
</ul>
<p><strong>Deviance</strong></p>
<ul>
<li>we use saturated and residual deviance to assess model, instead of <span class="math inline">\(R^2\)</span> or <span class="math inline">\(R^2(adj)\)</span></li>
<li>for a GLM model that fits the data well the approximate deviance <span class="math inline">\(D\)</span> is
<span class="math display">\[\chi^2(m-p)\]</span> where <span class="math inline">\(m\)</span> is the number of parameters in the saturated model (full model) and <span class="math inline">\(p\)</span> is the number of parameters in the model of interest</li>
<li>for our above model we have <span class="math inline">\(83.178 - 57.967 = 25.21\)</span> which is larger than 95th percentile of <span class="math inline">\(\chi^2(59-58)\)</span></li>
</ul>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="generalized-linear-models.html#cb52-1" aria-hidden="true"></a><span class="kw">qchisq</span>(<span class="dt">df=</span><span class="dv">1</span>, <span class="dt">p=</span><span class="fl">0.95</span>)</span>
<span id="cb52-2"><a href="generalized-linear-models.html#cb52-2" aria-hidden="true"></a><span class="co">## [1] 3.841459</span></span></code></pre></div>
<ul>
<li>i.e. <span class="math inline">\(25.21 &gt;&gt; 3.84\)</span> and again we can conclude that age is a significant term in the model</li>
</ul>
<p><strong>Odds ratios</strong></p>
<ul>
<li>In logistic regression we often interpret the model coefficients by taking <span class="math inline">\(e^{\hat{\beta}}\)</span></li>
<li>and we talk about <strong>odd ratios</strong></li>
<li>e.g. we can say, given our above model, <span class="math inline">\(e^{0.08943} = 1.093551\)</span> that for each unit increase in age the odds of hearing Laurel get multiplied by 1.09</li>
</ul>
<p><strong>Other covariates</strong></p>
<ul>
<li>Finally, we can use the same logic as in multiple regression to expand by models by additional variables, numerical, binary or categorical</li>
<li>E.g. we can test whether there is a gender effect when hearing Yanny or Laurel</li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="generalized-linear-models.html#cb53-1" aria-hidden="true"></a><span class="co"># fit logistic regression including age and gender</span></span>
<span id="cb53-2"><a href="generalized-linear-models.html#cb53-2" aria-hidden="true"></a>logmodel<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(word <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>gender, <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link=</span><span class="st">&quot;logit&quot;</span>), <span class="dt">data =</span> yl)</span>
<span id="cb53-3"><a href="generalized-linear-models.html#cb53-3" aria-hidden="true"></a></span>
<span id="cb53-4"><a href="generalized-linear-models.html#cb53-4" aria-hidden="true"></a><span class="co"># print model summary</span></span>
<span id="cb53-5"><a href="generalized-linear-models.html#cb53-5" aria-hidden="true"></a><span class="kw">print</span>(<span class="kw">summary</span>(logmodel<span class="fl">.2</span>))</span>
<span id="cb53-6"><a href="generalized-linear-models.html#cb53-6" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb53-7"><a href="generalized-linear-models.html#cb53-7" aria-hidden="true"></a><span class="co">## Call:</span></span>
<span id="cb53-8"><a href="generalized-linear-models.html#cb53-8" aria-hidden="true"></a><span class="co">## glm(formula = word ~ age + gender, family = binomial(link = &quot;logit&quot;), </span></span>
<span id="cb53-9"><a href="generalized-linear-models.html#cb53-9" aria-hidden="true"></a><span class="co">##     data = yl)</span></span>
<span id="cb53-10"><a href="generalized-linear-models.html#cb53-10" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb53-11"><a href="generalized-linear-models.html#cb53-11" aria-hidden="true"></a><span class="co">## Deviance Residuals: </span></span>
<span id="cb53-12"><a href="generalized-linear-models.html#cb53-12" aria-hidden="true"></a><span class="co">##      Min        1Q    Median        3Q       Max  </span></span>
<span id="cb53-13"><a href="generalized-linear-models.html#cb53-13" aria-hidden="true"></a><span class="co">## -1.81723  -0.72585  -0.06218   0.67360   2.44755  </span></span>
<span id="cb53-14"><a href="generalized-linear-models.html#cb53-14" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb53-15"><a href="generalized-linear-models.html#cb53-15" aria-hidden="true"></a><span class="co">## Coefficients:</span></span>
<span id="cb53-16"><a href="generalized-linear-models.html#cb53-16" aria-hidden="true"></a><span class="co">##             Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span id="cb53-17"><a href="generalized-linear-models.html#cb53-17" aria-hidden="true"></a><span class="co">## (Intercept) -3.72679    1.07333  -3.472 0.000516 ***</span></span>
<span id="cb53-18"><a href="generalized-linear-models.html#cb53-18" aria-hidden="true"></a><span class="co">## age          0.09061    0.02337   3.877 0.000106 ***</span></span>
<span id="cb53-19"><a href="generalized-linear-models.html#cb53-19" aria-hidden="true"></a><span class="co">## genderMale   0.23919    0.65938   0.363 0.716789    </span></span>
<span id="cb53-20"><a href="generalized-linear-models.html#cb53-20" aria-hidden="true"></a><span class="co">## ---</span></span>
<span id="cb53-21"><a href="generalized-linear-models.html#cb53-21" aria-hidden="true"></a><span class="co">## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb53-22"><a href="generalized-linear-models.html#cb53-22" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb53-23"><a href="generalized-linear-models.html#cb53-23" aria-hidden="true"></a><span class="co">## (Dispersion parameter for binomial family taken to be 1)</span></span>
<span id="cb53-24"><a href="generalized-linear-models.html#cb53-24" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb53-25"><a href="generalized-linear-models.html#cb53-25" aria-hidden="true"></a><span class="co">##     Null deviance: 83.178  on 59  degrees of freedom</span></span>
<span id="cb53-26"><a href="generalized-linear-models.html#cb53-26" aria-hidden="true"></a><span class="co">## Residual deviance: 57.835  on 57  degrees of freedom</span></span>
<span id="cb53-27"><a href="generalized-linear-models.html#cb53-27" aria-hidden="true"></a><span class="co">## AIC: 63.835</span></span>
<span id="cb53-28"><a href="generalized-linear-models.html#cb53-28" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb53-29"><a href="generalized-linear-models.html#cb53-29" aria-hidden="true"></a><span class="co">## Number of Fisher Scoring iterations: 5</span></span>
<span id="cb53-30"><a href="generalized-linear-models.html#cb53-30" aria-hidden="true"></a></span>
<span id="cb53-31"><a href="generalized-linear-models.html#cb53-31" aria-hidden="true"></a><span class="co"># plot model</span></span>
<span id="cb53-32"><a href="generalized-linear-models.html#cb53-32" aria-hidden="true"></a><span class="kw">ggPredict</span>(logmodel<span class="fl">.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-7"></span>
<img src="304-linear-GLM_files/figure-html/unnamed-chunk-7-1.png" alt="Yanny Laurel data modelled with logistic regression given age and gender. Regression lines in males and femals are very alike and the model suggest no gender effect" width="384" />
<p class="caption">
Figure 11.2: Yanny Laurel data modelled with logistic regression given age and gender. Regression lines in males and femals are very alike and the model suggest no gender effect
</p>
</div>
</div>
<div id="poisson-regression" class="section level2" number="11.4">
<h2><span class="header-section-number">11.4</span> Poisson regression</h2>
<ul>
<li>GLMs can be also applied to count data</li>
<li>e.g. hospital admissions due to respiratory disease or number of bird nests in a certain habitat</li>
<li>here, we commonly assume that data follow the Poisson distribution <span class="math inline">\(Y_i \sim Pois(\mu_i)\)</span></li>
<li>and the corresponding model is
<span class="math display">\[E(Y_i)=\mu_i = \eta_ie^{\mathbf{x_i}^T\boldsymbol\beta}\]</span> with a log link <span class="math inline">\(\ln\mu_i = \ln \eta_i + \mathbf{x_i}^T\boldsymbol\beta\)</span></li>
</ul>
<p><strong>Data set</strong>
Suppose we wish to model <span class="math inline">\(Y_i\)</span> the number of cancer cases in the i-th intermediate geographical location (IG) in Glasgow. We have collected data for 271 regions, a small areas that contain between 2500 and 6000 people. Together with cancer occurrence with have data:</p>
<ul>
<li>Y_all: number of cases of all types of cancer in te IG in 2013</li>
<li>E_all: expected number of cases of all types of cancer for the IG based on the population size and demographics of the IG in 2013</li>
<li>pm10: air pollution</li>
<li>smoke: percentage of people in an area that smoke</li>
<li>ethic: percentage of people who are non-white</li>
<li>logpice: natural log of average house price</li>
<li>easting and northing: co-ordinates of the central point of the IG divided by 10000</li>
</ul>
<p>We can model the <strong>rate of occurrence of cancer</strong> using the very same <code>glm</code> function:¨
- now we use <strong>poisson family distribution</strong> to model counts
- and we will include an <strong>offset term</strong> to model as we are modeling the rate of occurrence of the cancer that has to be adjusted by different number of people living in different regions</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="generalized-linear-models.html#cb54-1" aria-hidden="true"></a><span class="co"># Read in and preview data</span></span>
<span id="cb54-2"><a href="generalized-linear-models.html#cb54-2" aria-hidden="true"></a>cancer &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/lm/cancer.csv&quot;</span>)</span>
<span id="cb54-3"><a href="generalized-linear-models.html#cb54-3" aria-hidden="true"></a><span class="kw">head</span>(cancer)</span>
<span id="cb54-4"><a href="generalized-linear-models.html#cb54-4" aria-hidden="true"></a><span class="co">##          IG Y_all     E_all pm10 smoke ethnic log.price  easting northing</span></span>
<span id="cb54-5"><a href="generalized-linear-models.html#cb54-5" aria-hidden="true"></a><span class="co">## 1 S02000260   133 106.17907 17.8  21.9   5.58  11.59910 26.16245 66.96574</span></span>
<span id="cb54-6"><a href="generalized-linear-models.html#cb54-6" aria-hidden="true"></a><span class="co">## 2 S02000261    38  62.43131 18.6  21.8   7.91  11.84940 26.29271 67.00278</span></span>
<span id="cb54-7"><a href="generalized-linear-models.html#cb54-7" aria-hidden="true"></a><span class="co">## 3 S02000262    97 120.00694 18.6  20.8   9.58  11.74106 26.21429 67.04280</span></span>
<span id="cb54-8"><a href="generalized-linear-models.html#cb54-8" aria-hidden="true"></a><span class="co">## 4 S02000263    80 109.10245 17.0  14.0  10.39  12.30138 25.45705 67.05938</span></span>
<span id="cb54-9"><a href="generalized-linear-models.html#cb54-9" aria-hidden="true"></a><span class="co">## 5 S02000264   181 149.77821 18.6  15.2   5.67  11.88449 26.12484 67.09280</span></span>
<span id="cb54-10"><a href="generalized-linear-models.html#cb54-10" aria-hidden="true"></a><span class="co">## 6 S02000265    77  82.31156 17.0  14.6   5.61  11.82004 25.37644 67.09826</span></span>
<span id="cb54-11"><a href="generalized-linear-models.html#cb54-11" aria-hidden="true"></a></span>
<span id="cb54-12"><a href="generalized-linear-models.html#cb54-12" aria-hidden="true"></a><span class="co"># fit Poisson regression</span></span>
<span id="cb54-13"><a href="generalized-linear-models.html#cb54-13" aria-hidden="true"></a>epid1 &lt;-<span class="st"> </span><span class="kw">glm</span>(Y_all <span class="op">~</span><span class="st"> </span>pm10 <span class="op">+</span><span class="st"> </span>smoke <span class="op">+</span><span class="st"> </span>ethnic <span class="op">+</span><span class="st"> </span>log.price <span class="op">+</span><span class="st"> </span>easting <span class="op">+</span><span class="st"> </span>northing <span class="op">+</span><span class="st"> </span><span class="kw">offset</span>(<span class="kw">log</span>(E_all)), </span>
<span id="cb54-14"><a href="generalized-linear-models.html#cb54-14" aria-hidden="true"></a>             <span class="dt">family =</span> poisson, </span>
<span id="cb54-15"><a href="generalized-linear-models.html#cb54-15" aria-hidden="true"></a>             <span class="dt">data =</span> cancer)</span>
<span id="cb54-16"><a href="generalized-linear-models.html#cb54-16" aria-hidden="true"></a></span>
<span id="cb54-17"><a href="generalized-linear-models.html#cb54-17" aria-hidden="true"></a><span class="kw">print</span>(<span class="kw">summary</span>(epid1))</span>
<span id="cb54-18"><a href="generalized-linear-models.html#cb54-18" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb54-19"><a href="generalized-linear-models.html#cb54-19" aria-hidden="true"></a><span class="co">## Call:</span></span>
<span id="cb54-20"><a href="generalized-linear-models.html#cb54-20" aria-hidden="true"></a><span class="co">## glm(formula = Y_all ~ pm10 + smoke + ethnic + log.price + easting + </span></span>
<span id="cb54-21"><a href="generalized-linear-models.html#cb54-21" aria-hidden="true"></a><span class="co">##     northing + offset(log(E_all)), family = poisson, data = cancer)</span></span>
<span id="cb54-22"><a href="generalized-linear-models.html#cb54-22" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb54-23"><a href="generalized-linear-models.html#cb54-23" aria-hidden="true"></a><span class="co">## Deviance Residuals: </span></span>
<span id="cb54-24"><a href="generalized-linear-models.html#cb54-24" aria-hidden="true"></a><span class="co">##     Min       1Q   Median       3Q      Max  </span></span>
<span id="cb54-25"><a href="generalized-linear-models.html#cb54-25" aria-hidden="true"></a><span class="co">## -4.2011  -0.9338  -0.1763   0.8959   3.8416  </span></span>
<span id="cb54-26"><a href="generalized-linear-models.html#cb54-26" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb54-27"><a href="generalized-linear-models.html#cb54-27" aria-hidden="true"></a><span class="co">## Coefficients:</span></span>
<span id="cb54-28"><a href="generalized-linear-models.html#cb54-28" aria-hidden="true"></a><span class="co">##               Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span id="cb54-29"><a href="generalized-linear-models.html#cb54-29" aria-hidden="true"></a><span class="co">## (Intercept) -0.8592657  0.8029040  -1.070 0.284531    </span></span>
<span id="cb54-30"><a href="generalized-linear-models.html#cb54-30" aria-hidden="true"></a><span class="co">## pm10         0.0500269  0.0066724   7.498 6.50e-14 ***</span></span>
<span id="cb54-31"><a href="generalized-linear-models.html#cb54-31" aria-hidden="true"></a><span class="co">## smoke        0.0033516  0.0009463   3.542 0.000397 ***</span></span>
<span id="cb54-32"><a href="generalized-linear-models.html#cb54-32" aria-hidden="true"></a><span class="co">## ethnic      -0.0049388  0.0006354  -7.773 7.66e-15 ***</span></span>
<span id="cb54-33"><a href="generalized-linear-models.html#cb54-33" aria-hidden="true"></a><span class="co">## log.price   -0.1034461  0.0169943  -6.087 1.15e-09 ***</span></span>
<span id="cb54-34"><a href="generalized-linear-models.html#cb54-34" aria-hidden="true"></a><span class="co">## easting     -0.0331305  0.0103698  -3.195 0.001399 ** </span></span>
<span id="cb54-35"><a href="generalized-linear-models.html#cb54-35" aria-hidden="true"></a><span class="co">## northing     0.0300213  0.0111013   2.704 0.006845 ** </span></span>
<span id="cb54-36"><a href="generalized-linear-models.html#cb54-36" aria-hidden="true"></a><span class="co">## ---</span></span>
<span id="cb54-37"><a href="generalized-linear-models.html#cb54-37" aria-hidden="true"></a><span class="co">## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb54-38"><a href="generalized-linear-models.html#cb54-38" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb54-39"><a href="generalized-linear-models.html#cb54-39" aria-hidden="true"></a><span class="co">## (Dispersion parameter for poisson family taken to be 1)</span></span>
<span id="cb54-40"><a href="generalized-linear-models.html#cb54-40" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb54-41"><a href="generalized-linear-models.html#cb54-41" aria-hidden="true"></a><span class="co">##     Null deviance: 972.94  on 270  degrees of freedom</span></span>
<span id="cb54-42"><a href="generalized-linear-models.html#cb54-42" aria-hidden="true"></a><span class="co">## Residual deviance: 565.18  on 264  degrees of freedom</span></span>
<span id="cb54-43"><a href="generalized-linear-models.html#cb54-43" aria-hidden="true"></a><span class="co">## AIC: 2356.2</span></span>
<span id="cb54-44"><a href="generalized-linear-models.html#cb54-44" aria-hidden="true"></a><span class="co">## </span></span>
<span id="cb54-45"><a href="generalized-linear-models.html#cb54-45" aria-hidden="true"></a><span class="co">## Number of Fisher Scoring iterations: 4</span></span></code></pre></div>
<p><strong>Hypothesis testing, model fit and predictions</strong></p>
<ul>
<li>follows stay the same as for logistic regression</li>
</ul>
<p><strong>Rate ratio</strong></p>
<ul>
<li>similarly to logistic regression it common to look at the <span class="math inline">\(e^\beta\)</span></li>
<li>for instance we are interested in the effect of air pollution on health, we could look at the pm10 coefficient</li>
<li>coefficient is positive, 0.0500269, indicating that cancer incidence rate increase with increased air poluttion</li>
<li>the rate ratio allows us to quantify by how much, here by a factor of <span class="math inline">\(e^{0.0500269} = 1.05\)</span></li>
</ul>
<hr />
</div>
<div id="exercises-glms" class="section level2" number="11.5">
<h2><span class="header-section-number">11.5</span> Exercises (GLMs)</h2>
<p>Data for exercises</p>
<ul>
<li><a href="https://github.com/olgadet/bookdown-mlbiostatistics/tree/master/data/lm/data.zip">Link 1</a></li>
<li><a href="https://stockholmuniversity.box.com/s/z5kwg0nlwe5la4h5t8bshpj57pylif14">Alternative Link 2</a></li>
</ul>

<div class="exercise">
<p><span id="exr:glm-yanny" class="exercise"><strong>Exercise 11.1  </strong></span>Our own Yanny or Laurel dataset</p>
<p>Exploratory data analysis:</p>
<ol style="list-style-type: lower-alpha">
<li>load the data that we have collected earlier on “yanny-laurel-us.cvs”</li>
<li>plot the data to explore some basic relationships between every pair of variables</li>
<li>are they any outing values, e.g. someone claiming to be too young or too skinny? Remove these observations.</li>
</ol>
<p>Logistic regression:</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>fit a logistic linear regression model to check whether age is associated with the probability of hearing Laurel? What are the odds of hearing Laurel in our group when we get one year older?</li>
<li>are any other variables associated with hearing different words? Height? Weight? BMI? Commuting by bike?</li>
<li>if someone is 40 years of old, with 162cm, 60kg and cycling to work, what is the most likely world he/she hears?</li>
</ol>
<p>Poisson regression:</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>fit a Poisson regression to model number of Facebook friends (no need to use offset here)</li>
<li>can you explain the number of Facebook friends with any of the variables collected?</li>
<li>if someone is 40 years of old, with 162cm, 60kg and cycling to work, how many Facebook friends he/she has?</li>
</ol>
</div>

<div class="exercise">
<p><span id="exr:glm-wcgs" class="exercise"><strong>Exercise 11.2  </strong></span>
Additional practice</p>
<p>More practice with bigger more realistic data set. We have not analyzed the data ourselves yet. Let us know what you find. Anything goes.</p>
<p>What might affect the chance of getting a heart disease? One of the earliest studies addressing this issue started in 1960 in 3154 healthy men in the San Francisco area. At the start of the study all were free of heart disease. Eight years later the study recorded whether these men now suffered from heart disease (chd), along with many other variables that might be related. The data is available from faraway package:</p>
<ul>
<li>using logistic regression, can you discover anything interesting about the probability of developing heart disease</li>
<li>using Poisson regression, can you comment about number of cigarettes smoked?</li>
</ul>
</div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="generalized-linear-models.html#cb55-1" aria-hidden="true"></a></span>
<span id="cb55-2"><a href="generalized-linear-models.html#cb55-2" aria-hidden="true"></a><span class="kw">library</span>(faraway)</span>
<span id="cb55-3"><a href="generalized-linear-models.html#cb55-3" aria-hidden="true"></a><span class="kw">data</span>(wcgs, <span class="dt">package=</span><span class="st">&quot;faraway&quot;</span>)</span>
<span id="cb55-4"><a href="generalized-linear-models.html#cb55-4" aria-hidden="true"></a></span>
<span id="cb55-5"><a href="generalized-linear-models.html#cb55-5" aria-hidden="true"></a><span class="kw">head</span>(wcgs)</span>
<span id="cb55-6"><a href="generalized-linear-models.html#cb55-6" aria-hidden="true"></a><span class="co">##      age height weight sdp dbp chol behave cigs dibep chd  typechd timechd</span></span>
<span id="cb55-7"><a href="generalized-linear-models.html#cb55-7" aria-hidden="true"></a><span class="co">## 2001  49     73    150 110  76  225     A2   25     B  no     none    1664</span></span>
<span id="cb55-8"><a href="generalized-linear-models.html#cb55-8" aria-hidden="true"></a><span class="co">## 2002  42     70    160 154  84  177     A2   20     B  no     none    3071</span></span>
<span id="cb55-9"><a href="generalized-linear-models.html#cb55-9" aria-hidden="true"></a><span class="co">## 2003  42     69    160 110  78  181     B3    0     A  no     none    3071</span></span>
<span id="cb55-10"><a href="generalized-linear-models.html#cb55-10" aria-hidden="true"></a><span class="co">## 2004  41     68    152 124  78  132     B4   20     A  no     none    3064</span></span>
<span id="cb55-11"><a href="generalized-linear-models.html#cb55-11" aria-hidden="true"></a><span class="co">## 2005  59     70    150 144  86  255     B3   20     A yes infdeath    1885</span></span>
<span id="cb55-12"><a href="generalized-linear-models.html#cb55-12" aria-hidden="true"></a><span class="co">## 2006  44     72    204 150  90  182     B4    0     A  no     none    3102</span></span>
<span id="cb55-13"><a href="generalized-linear-models.html#cb55-13" aria-hidden="true"></a><span class="co">##        arcus</span></span>
<span id="cb55-14"><a href="generalized-linear-models.html#cb55-14" aria-hidden="true"></a><span class="co">## 2001  absent</span></span>
<span id="cb55-15"><a href="generalized-linear-models.html#cb55-15" aria-hidden="true"></a><span class="co">## 2002 present</span></span>
<span id="cb55-16"><a href="generalized-linear-models.html#cb55-16" aria-hidden="true"></a><span class="co">## 2003  absent</span></span>
<span id="cb55-17"><a href="generalized-linear-models.html#cb55-17" aria-hidden="true"></a><span class="co">## 2004  absent</span></span>
<span id="cb55-18"><a href="generalized-linear-models.html#cb55-18" aria-hidden="true"></a><span class="co">## 2005 present</span></span>
<span id="cb55-19"><a href="generalized-linear-models.html#cb55-19" aria-hidden="true"></a><span class="co">## 2006  absent</span></span></code></pre></div>

</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="model-summary-assumptions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="classification-with-knn-and-decision-trees.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Introduction-to-biostatistics-and-machine-learning.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
